create database guest USING CODESET UTF-8 TERRITORY US COLLATE USING SYSTEM PAGESIZE 32768 @
connect to guest user guest using guestGU3sT @
-- connect as db2inst1
connect to guest @

CREATE BUFFERPOOL BP32K IMMEDIATE SIZE 250 AUTOMATIC PAGESIZE 32K @
CREATE LARGE TABLESPACE TS32K PAGESIZE 32K MANAGED BY AUTOMATIC STORAGE BUFFERPOOL BP32K @
CREATE BUFFERPOOL BP32 SIZE 2000 PAGESIZE 32K @
CREATE SYSTEM TEMPORARY TABLESPACE STB_32 PAGESIZE 32K @

-- force SYSTOOLS schema creation
BEGIN
  DECLARE tmp INT;
  CALL SYSPROC.DB2LK_GENERATE_DDL('-e -t sysibm.sysdummy1', tmp);
END @
GRANT DATAACCESS ON DATABASE TO USER guest @
CALL SYSPROC.SYSINSTALLOBJECTS('EXPLAIN', 'C', 
        CAST (NULL AS VARCHAR(128)), CAST (NULL AS VARCHAR(128))) @














